# Generated by Django 4.0.4 on 2022-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='time_ending',
        ),
        migrations.AddField(
            model_name='schedules',
            name='day',
            field=models.CharField(choices=[('1', 'Freshman'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior'), ('5', 'Graduate'), ('6', 'Graduate')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedules',
            name='text',
            field=models.CharField(default=1, max_length=355),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedules',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='time_begining',
            field=models.CharField(choices=[('9', 'Freshman'), ('11', 'Sophomore'), ('14', 'Junior'), ('18', 'Senior')], max_length=255),
        ),
    ]
