# Generated by Django 4.0.4 on 2022-04-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_schedules_date_remove_schedules_time_ending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='day',
            field=models.CharField(choices=[('1', 'Freshman'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior'), ('5', 'beshnisa'), ('6', 'Graduate')], max_length=255),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='time_begining',
            field=models.TimeField(),
        ),
    ]
