# Generated by Django 4.0.4 on 2022-04-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_schedules_day_alter_schedules_time_begining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedules',
            options={'ordering': ['time_begining'], 'verbose_name': 'Schedules', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterField(
            model_name='schedules',
            name='day',
            field=models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'ЧЕТВЕРГ'), ('5', 'ПЯТНИЦА'), ('6', 'СУББОТА')], max_length=255),
        ),
    ]
