# Generated by Django 4.0.4 on 2022-05-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_schedules_options_alter_schedules_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='day',
            field=models.CharField(choices=[('1', 'ПОНЕДЕЛЬНИК'), ('2', 'ВТОРНИК'), ('3', 'СРЕДА'), ('4', 'ЧЕТВЕРГ'), ('5', 'ПЯТНИЦА'), ('6', 'СУББОТА')], max_length=255),
        ),
    ]
